version: '3.8'

services:
  nest-app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/e-commerce-db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: e-commerce-db
