version: '3.8'

services:
  api:
    image: sim-ecommerce-api:2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3030:3005"
    networks:
      - sim-ecommerce
    depends_on:
      - storage

  storage:
    image: mongo:latest
    container_name: sim-ecommerce-mongo
    ports:
      - "27017:27017"
    networks:
      - sim-ecommerce

networks:
  sim-ecommerce:
    driver: bridge
